// AUTO-GENERATED by import-amazon.mjs.
// Real Amazon.co.jp product links resolved via the Product Advertising API
// (PA-API 5.0) SearchItems operation, matched by product name. Empty until
// import-amazon.mjs has been run with valid PA-API credentials — see that
// file's header comment for setup. Until then lib/affiliates.ts falls back
// to a tagged Amazon search link per product.
export const amazonLinks: Record<string, string> = {};
