'use client';
import { useState,useEffect } from 'react';
import Link from 'next/link';
import { products,categories,disasters,displayStats,type Review } from '@/lib/catalog';
import {ProductCard} from './site';
import { Input } from './ui/input';
import { NativeSelect } from './ui/native-select';
import { Button } from './ui/button';
import {Search,SlidersHorizontal} from 'lucide-react';
type Filters={q?:string;category?:string;disaster?:string;rating?:string;sort?:string};
export function CatalogView({reviews,initial={},ranking=false}:{reviews:Review[];initial?:Filters;ranking?:boolean}){
 const [q,setQ]=useState(initial.q||''),[category,setCategory]=useState(initial.category||''),[disaster,setDisaster]=useState(initial.disaster||''),[rating,setRating]=useState(initial.rating||''),[sort,setSort]=useState(initial.sort||(ranking?'rating':'new')),[price,setPrice]=useState(''),[brand,setBrand]=useState(''),[count,setCount]=useState('');
 const filtered=products.filter(p=>{const s=displayStats(p,reviews);const hay=[p.name,p.category,p.brand,p.disasters.join(' '),p.goodFor,...reviews.filter(r=>r.productId===p.id).map(r=>r.title+' '+r.body)].join(' ').normalize('NFKC').toLowerCase();return q.normalize('NFKC').toLowerCase().split(/\s+/).every(t=>hay.includes(t))&&(!category||p.category===category)&&(!disaster||p.disasters.includes(disaster))&&(!rating||s.average>=Number(rating))&&(!price||p.price<=Number(price))&&(!brand||p.brand===brand)&&(!count||s.count>=Number(count))}).sort((a,b)=>sort==='rating'?displayStats(b,reviews).average-displayStats(a,reviews).average:sort==='count'?displayStats(b,reviews).count-displayStats(a,reviews).count:sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.added.localeCompare(a.added));
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'search_disaster_products',description:'商品一覧の検索語を設定し、表示対象の商品IDを返します。',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const value=input as {query?:unknown};if(typeof value?.query!=='string'||value.query.length>100)throw new Error('query must be a string of at most 100 characters');setQ(value.query);setCategory('');setDisaster('');setRating('');setPrice('');setBrand('');setCount('');await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {query:value.query};}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const reset=()=>{setQ('');setCategory('');setDisaster('');setRating('');setPrice('');setBrand('');setCount('')};
 return <><div className="catalog-search"><Search size={22}/><Input aria-label="商品・口コミを検索" placeholder="商品名・口コミ・カテゴリを検索" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="catalog-layout"><aside className="filters"><h2><SlidersHorizontal size={18}/>条件で絞り込む</h2>{[['カテゴリ',category,setCategory,categories],['災害の種類',disaster,setDisaster,disasters],['メーカー',brand,setBrand,[...new Set(products.map(p=>p.brand))]]].map(([label,value,set,options])=><label key={String(label)}>{String(label)}<NativeSelect value={String(value)} onChange={e=>(set as (v:string)=>void)(e.target.value)}><option value="">すべて</option>{(options as string[]).map(x=><option key={x}>{x}</option>)}</NativeSelect></label>)}<label>価格帯<NativeSelect value={price} onChange={e=>setPrice(e.target.value)}><option value="">指定なし</option><option value="3000">3,000円以下</option><option value="5000">5,000円以下</option><option value="10000">10,000円以下</option></NativeSelect></label><label>評価<NativeSelect value={rating} onChange={e=>setRating(e.target.value)}><option value="">指定なし</option><option value="4.5">★4.5以上</option><option value="4">★4以上</option><option value="3">★3以上</option></NativeSelect></label><label>口コミ件数<NativeSelect value={count} onChange={e=>setCount(e.target.value)}><option value="">指定なし</option><option value="1">1件以上</option><option value="5">5件以上</option><option value="10">10件以上</option></NativeSelect></label><Button variant="outline" onClick={reset}>条件をクリア</Button></aside><div><div className="results-bar"><p aria-live="polite"><strong>{filtered.length}</strong> 件の商品</p><NativeSelect aria-label="並び替え" value={sort} onChange={e=>setSort(e.target.value)}><option value="rating">評価が高い順</option><option value="count">口コミが多い順</option><option value="new">新着順</option><option value="low">価格が安い順</option><option value="high">価格が高い順</option></NativeSelect></div>{filtered.length?<div className="product-grid three">{filtered.map((p,i)=><ProductCard product={p} key={p.id} rank={ranking?i+1:undefined} reviews={reviews}/>)}</div>:<div className="empty-state"><h2>条件に合う商品が見つかりませんでした</h2><p>検索語を短くするか、絞り込み条件を変更してください。</p><Button onClick={reset}>すべての商品を見る</Button></div>}</div></div></>
}
