'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Flag,Share2} from 'lucide-react';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from './ui/dialog';
import {Rating} from './site';
import {type Review} from '@/lib/catalog';
export function ReviewCard({review:r}:{review:Review}){const [message,setMessage]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);async function report(){setBusy(true);try{const res=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewId:r.id,reason})});const data=await res.json();setMessage(res.ok?'通報を受け付けました。':data.error)}catch{setMessage('送信できませんでした。もう一度お試しください。')}finally{setBusy(false)}}return <article className="review-full" id={r.id}><div className="review-meta"><span className="avatar">{r.nickname[0]}</span><strong>{r.nickname}</strong><time>{r.createdAt.slice(0,10)}</time></div><div className="review-tags"><span>購入・使用状況は自己申告</span></div><Rating average={r.rating}/><h3><Link href={`/reviews/${r.id}`}>{r.title}</Link></h3><p className="review-body">{r.body}</p><div className="review-photos">{r.images.map((src,i)=><a href={src} target="_blank" rel="noreferrer" key={src}><img src={src} alt={`${r.nickname}さんの口コミ写真 ${i+1}`} loading="lazy"/></a>)}</div><div className="review-actions"><Button variant="ghost" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/reviews/${r.id}`);setMessage('口コミのURLをコピーしました。')}catch{setMessage('コピーできませんでした。口コミタイトルから開いたページのURLをご利用ください。')}}}><Share2/>共有</Button><Dialog><DialogTrigger asChild><Button variant="ghost"><Flag/>通報</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>この口コミを通報する</DialogTitle><DialogDescription>個人情報や不適切な内容など、気になる点を教えてください。</DialogDescription></DialogHeader><Textarea aria-label="通報理由" value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500}/><Button onClick={report} disabled={busy||reason.trim().length<5}>{busy?'送信中…':'通報を送信'}</Button><p role="status">{message}</p></DialogContent></Dialog></div>{message&&<p role="status" className="muted">{message}</p>}</article>}
