'use client';
import Link from 'next/link';
import { Search, ShieldCheck, PenLine, ArrowUpRight, ArrowRight, Tent, CloudRain, Zap, House, Wind, Flashlight, Backpack, BatteryCharging, Utensils, ChevronRight, MessageCircle, Camera } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { products, displayStats, yen, type Product, type Review, categories } from '@/lib/catalog';
export function Header(){return <><div className="top-note">いつもの暮らしに、ちょっとずつの備えを。</div><header className="header"><Link href="/" className="brand"><span className="brand-icon"><ShieldCheck/></span><span>そなえレビュー<small>SONAE REVIEW</small></span></Link><nav aria-label="メインナビゲーション"><Link href="/guide">状況から選ぶ</Link><Link href="/products">商品を探す</Link><Link href="/ranking">ランキング</Link><Link href="/categories">カテゴリ</Link></nav><Button asChild className="write-button"><Link href="/products"><PenLine/>口コミを書く</Link></Button></header></>}
export function Footer(){return <footer><div className="footer-inner"><Link className="brand" href="/"><ShieldCheck/>そなえレビュー</Link><p>ひとつの口コミが、だれかの備えになる。</p><div><Link href="/guidelines">投稿ガイドライン</Link><Link href="/about">運営方針・広告について</Link><Link href="/categories">カテゴリ一覧</Link></div><small>© 2026 そなえレビュー</small></div></footer>}
export function SearchBox({large=false,initial=''}:{large?:boolean;initial?:string}){return <form action="/products" className={`search-box ${large?'large':''}`}><Search size={21}/><Input aria-label="商品・口コミを検索" name="q" defaultValue={initial} placeholder="気になる防災グッズを検索"/><Button type="submit">検索する</Button></form>}
export function ProductImage({product,className=''}:{product:Product;className?:string}){if(product.image)return <img src={product.image} alt={product.name} className={`product-image ${className}`} style={{objectFit:'contain'}}/>;return <div role="img" aria-label={`${product.name}の画像`} className={`product-image tile-${product.tile ?? 0} ${className}`}/>}
export function Rating({average,count}:{average:number;count?:number}){return <span className="rating"><span className="stars" aria-label={`5点満点中${average.toFixed(1)}点`}>★</span><strong>{average?average.toFixed(1):'—'}</strong>{count!==undefined&&<span className="muted">（{count}件）</span>}</span>}
export function ProductCard({product,rank,reviews=[]}:{product:Product;rank?:number;reviews?:Review[]}){return <Link className="product-card" href={`/products/${product.id}`}><div className="image-wrap"><ProductImage product={product}/>{rank&&<span className={`rank rank-${rank}`}>{String(rank).padStart(2,'0')}</span>}<span className="image-label">楽天</span></div><div className="product-copy"><span className="eyebrow">{product.category}</span><h3>{product.name}</h3><Rating {...displayStats(product,reviews)}/><p className="card-price">{yen(product.price)}<small>楽天価格</small></p></div></Link>}
const disasterIcons=[House,Wind,CloudRain,Zap,Tent];
export function SectionTitle({eyebrow,title,href,link='すべて見る'}:{eyebrow:string;title:string;href?:string;link?:string}){return <div className="section-title"><div><p className="overline">{eyebrow}</p><h2>{title}</h2></div>{href&&<Link href={href}>{link}<ArrowRight size={17}/></Link>}</div>}
export function HomePage(){return <main><section className="hero"><div className="hero-copy"><p className="hero-kicker">みんなの経験で、備えをもっと身近に。</p><h1>その防災グッズ、<br/>本当に<span>使える？</span></h1><p className="hero-sub">買う前に、使った人のリアルな口コミを。</p><SearchBox large/><div className="popular-words"><span>人気の検索</span>{['簡易トイレ','停電','防災バッグ'].map(x=><Link key={x} href={`/products?q=${encodeURIComponent(x)}`}>{x}<ChevronRight size={13}/></Link>)}</div></div><div className="hero-visual"><div className="hero-photo"><ProductImage product={products.find(p=>p.category==='防災バッグ')||products[0]}/><span className="photo-note">MY EVERYDAY, MY PREPAREDNESS.</span></div><div className="floating-note"><span className="floating-stars">★★★★★</span><strong>「実際に入れて、背負ってみた。」</strong><span><Camera size={15}/>写真でわかる、暮らしの中の備え</span></div><span className="hero-tag">備えるって、<br/>暮らしを想うこと。</span></div></section><div className="trust-strip"><span><Camera/>写真でわかる使用感</span><span><MessageCircle/>良い点も、気になる点も</span><span><ShieldCheck/>使った人の目線で選ぶ</span></div><div className="content"><section className="section"><SectionTitle eyebrow="COMMUNITY FAVORITES" title="使った人に、選ばれたもの。" href="/ranking" link="ランキングを見る"/><div className="section-description">みんなの評価から見つける、あなたに合う備え。<span>評価順</span></div><div className="product-grid">{[...products].sort((a,b)=>displayStats(b).average-displayStats(a).average).slice(0,4).map((p,i)=><ProductCard product={p} rank={i+1} key={p.id}/>)}</div></section><section className="section disaster-section"><SectionTitle eyebrow="PREPARE FOR" title="どんな「もしも」に備える？" href="/guide" link="家族構成も選んで探す"/><div className="disaster-grid">{['地震','台風','大雨','停電','避難'].map((x,i)=>{const Icon=disasterIcons[i];return <Link key={x} href={`/guide?d=${encodeURIComponent(x)}`}><Icon/><span>{x}に備える</span><ArrowUpRight size={16}/></Link>})}</div></section><section className="section"><SectionTitle eyebrow="FIND YOUR ESSENTIALS" title="防災グッズから探す" href="/categories" link="カテゴリ一覧"/><div className="category-grid">{[Tent,Flashlight,Backpack,BatteryCharging,Utensils,BatteryCharging].map((Icon,i)=><Link href={`/categories/${i}`} key={i}><span><Icon/></span><strong>{categories[i]}</strong><ChevronRight size={16}/></Link>)}</div></section><section className="section"><SectionTitle eyebrow="HIGHLY RATED" title="高評価の備えをチェック" href="/products?rating=4.5"/><div className="product-grid three">{products.filter(p=>displayStats(p).average>=4.5).slice(0,12).map(p=><ProductCard product={p} key={p.id}/>)}</div></section><section className="contribute"><div><p className="overline">YOUR EXPERIENCE MATTERS</p><h2>あなたの「使ってみた」が、<br/>だれかの安心につながる。</h2><p>よかったことも、ちょっと気になったことも。<br/>写真と一緒に、あなたの備えを教えてください。</p></div><Button asChild><Link href="/products"><PenLine/>口コミを書いてみる<ArrowRight/></Link></Button></section></div></main>}
